#!/bin/bash
#
# Wrapper around BitTorrent client to control UFW firewall rules


# BitTorrent client
TARGET='transmission-gtk'


# check for other running instances of current program
isunique(){
    [[ $(pidof -x "$0") = "$$" ]]
}


if (( $# == 1 )) && [[ $1 =~ ^(-h|--help)$ ]]; then
    cat <<-EOF
	Usage: ${0##*/} [ARGUMENT...]

	Wrapper around $TARGET to control UFW firewall rules.
	EOF
    exit 0
fi

if isunique; then
    sudo torrential allow
fi

"$TARGET" "$@"

if isunique; then
    sudo torrential deny
fi
